version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: heartsight_db
      POSTGRES_USER: heartsight
      POSTGRES_PASSWORD: heartsight
    volumes: ["db_data:/var/lib/postgresql/data"]
  cache:
    image: redis:7
  backend:
    build: ./server
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, cache]
volumes:
  db_data:
